const REVIEW_KEY='kenzy-quiz-review-v1';
let quizObserver;
let quizState=loadState();
let lastSignature='';
function loadState(){try{return JSON.parse(sessionStorage.getItem(REVIEW_KEY)||'{}');}catch{return {};}}
function saveState(){sessionStorage.setItem(REVIEW_KEY,JSON.stringify(quizState));}
function currentNumber(page){const match=page.querySelector('.question-count')?.textContent.match(/Question\s+(\d+)/i);return match?Number(match[1]):1;}
function totalNumber(page){const match=page.querySelector('.question-count')?.textContent.match(/of\s+(\d+)/i);return match?Number(match[1]):1;}
function setupQuiz(){
 const page=document.querySelector('.quiz-page');
 if(!page){document.getElementById('quiz-upgrade-panel')?.remove();document.getElementById('kenzy-share-panel')?.remove();lastSignature='';return;}
 const total=totalNumber(page), current=currentNumber(page); const selected=!!page.querySelector('.answer-button.selected');
 if(!quizState.id || quizState.total!==total){quizState={id:`quiz-${Date.now()}`,total,answered:{},marked:{}};saveState();}
 quizState.answered[current]=selected; saveState();
 const signature=`${total}|${current}|${selected}|${JSON.stringify(quizState.marked)}|${JSON.stringify(quizState.answered)}`;
 if(signature===lastSignature && document.getElementById('quiz-upgrade-panel'))return;
 lastSignature=signature;
 let panel=document.getElementById('quiz-upgrade-panel');
 if(!panel){panel=document.createElement('section');panel.id='quiz-upgrade-panel';panel.className='quiz-upgrade-panel';const toolbar=page.querySelector('.quiz-toolbar');toolbar?.after(panel);}
 panel.innerHTML=`<div class="quiz-upgrade-head"><div><strong>Question navigator</strong><small>Jump to a question or mark one to review later.</small></div><button class="quiz-mark-button ${quizState.marked[current]?'marked':''}" type="button">${quizState.marked[current]?'★ Marked for review':'☆ Mark for review'}</button></div><div class="quiz-upgrade-grid">${Array.from({length:total},(_,i)=>{const n=i+1;return `<button type="button" class="quiz-grid-dot ${n===current?'current':''} ${quizState.answered[n]?'answered':''} ${quizState.marked[n]?'marked':''}" data-q="${n}">${n}</button>`}).join('')}</div><div class="quiz-upgrade-legend"><span><i class="current"></i> Current</span><span><i class="answered"></i> Answered</span><span><i class="marked"></i> Review</span></div>`;
 panel.querySelector('.quiz-mark-button').onclick=()=>{quizState.marked[current]=!quizState.marked[current];saveState();lastSignature='';setupQuiz();};
 panel.querySelectorAll('[data-q]').forEach(btn=>btn.onclick=()=>jumpTo(page,Number(btn.dataset.q),current));
 [...page.querySelectorAll('.quiz-navigation .primary')].forEach(btn=>{if(btn.dataset.warnBound==='1')return;btn.dataset.warnBound='1';btn.addEventListener('click',event=>{if(!/^Submit quiz/i.test(btn.textContent.trim()))return;const unanswered=Array.from({length:total},(_,i)=>i+1).filter(n=>!quizState.answered[n]);if(unanswered.length&&!window.confirm(`You have ${unanswered.length} unanswered question${unanswered.length===1?'':'s'}. Submit anyway?`)){event.preventDefault();event.stopImmediatePropagation();}},true);});
}
function jumpTo(page,target,current){if(target===current)return;const next=target>current;const button=[...page.querySelectorAll('.quiz-navigation button')].find(b=>next?/Next/.test(b.textContent):/Previous/.test(b.textContent));if(!button)return;let steps=Math.abs(target-current);const tick=()=>{if(steps<=0){lastSignature='';setupQuiz();return;}button.click();steps--;setTimeout(tick,35);};tick();}
function boot(){if(quizObserver)return;quizObserver=new MutationObserver(()=>{if(document.querySelector('.quiz-page'))setupQuiz();});quizObserver.observe(document.body,{childList:true,subtree:true});setupQuiz();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();

const SHARE_VIS_KEY='kenzy-quiz-visibility-v1';
function shareEncode(q){const b=new TextEncoder().encode(JSON.stringify({title:q.title,timeLimit:q.timeLimit,questions:q.questions}));let s='';b.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function shareDecode(t){try{t=t.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-t.length%4)%4);const s=atob(t),b=Uint8Array.from(s,c=>c.charCodeAt(0));const q=JSON.parse(new TextDecoder().decode(b));return q&&Array.isArray(q.questions)&&q.questions.length?q:null;}catch{return null;}}
function shareUrl(q){return location.origin+location.pathname+'#quiz='+encodeURIComponent(shareEncode(q));}
function shareStyle(){if(document.getElementById('kenzy-share-style'))return;const s=document.createElement('style');s.id='kenzy-share-style';s.textContent='.kenzy-visibility-panel{margin-top:16px;padding:18px;background:var(--surface);border:1px solid var(--border);border-radius:18px}.kenzy-visibility-panel strong{color:var(--text)}.kenzy-visibility-panel small{display:block;margin-top:4px;color:var(--muted);line-height:1.4}.kenzy-visibility-options{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.kenzy-visibility-option{display:flex;gap:10px;padding:13px;border:1px solid var(--border);border-radius:14px;background:var(--surface2);cursor:pointer}.kenzy-visibility-option.selected{border-color:var(--accent);box-shadow:0 0 0 3px rgba(91,85,232,.12)}.kenzy-visibility-option input{accent-color:var(--accent)}.kenzy-share-panel{margin:0 0 20px;padding:18px;background:var(--soft);border:1px solid var(--border);border-radius:18px}.kenzy-share-panel strong{color:var(--text);display:block}.kenzy-share-panel small{color:var(--muted);display:block;margin-top:4px}.kenzy-share-row{display:flex;gap:8px;margin-top:12px}.kenzy-share-row input{min-width:0;flex:1;padding:10px;border:1px solid var(--border);border-radius:10px;background:var(--surface);color:var(--text)}.kenzy-share-row button{border:0;border-radius:10px;padding:10px 14px;background:var(--accent);color:#fff;font-weight:800}.kenzy-share-note{margin-top:9px!important;font-size:11px}@media(max-width:600px){.kenzy-visibility-options{grid-template-columns:1fr}.kenzy-share-row{flex-direction:column}}';document.head.appendChild(s);}
function shareAccess(){shareStyle();const page=[...document.querySelectorAll('.page')].find(p=>[...p.querySelectorAll('button')].some(b=>/Generate quiz/i.test(b.textContent)));if(!page||document.getElementById('kenzy-visibility-panel'))return;const mode=sessionStorage.getItem(SHARE_VIS_KEY)||'personal';const p=document.createElement('section');p.id='kenzy-visibility-panel';p.className='kenzy-visibility-panel';p.innerHTML=`<strong>Quiz access</strong><small>Choose whether this quiz is personal or shareable with friends.</small><div class="kenzy-visibility-options"><label class="kenzy-visibility-option ${mode==='personal'?'selected':''}"><input type="radio" name="kenzy-visibility" value="personal" ${mode==='personal'?'checked':''}><span><b>Personal</b><small>Keep it in your Kenzy app like the original quiz.</small></span></label><label class="kenzy-visibility-option ${mode==='shareable'?'selected':''}"><input type="radio" name="kenzy-visibility" value="shareable" ${mode==='shareable'?'checked':''}><span><b>Shareable</b><small>Create a link friends can open and answer.</small></span></label></div>`;const btn=[...page.querySelectorAll('button')].find(b=>/Generate quiz/i.test(b.textContent));btn.parentElement?.before(p);p.querySelectorAll('input').forEach(i=>i.onchange=()=>{sessionStorage.setItem(SHARE_VIS_KEY,i.value);p.querySelectorAll('.kenzy-visibility-option').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked));});}
function markLatestShareable(){try{const q=JSON.parse(localStorage.getItem('kenzy-quizzes-v4')||'[]');if(!q.length)return;const mode=sessionStorage.getItem(SHARE_VIS_KEY)||'personal';q[0].visibility=mode;localStorage.setItem('kenzy-quizzes-v4',JSON.stringify(q));}catch{}}
function shareOnQuiz(){markLatestShareable();const page=document.querySelector('.quiz-page');if(!page)return;let q;try{q=JSON.parse(localStorage.getItem('kenzy-quizzes-v4')||'[]')[0];}catch{}if(!q||q.visibility!=='shareable'||document.getElementById('kenzy-share-panel'))return;const u=shareUrl(q),p=document.createElement('section');p.id='kenzy-share-panel';p.className='kenzy-share-panel';p.innerHTML=`<strong>Share this quiz with friends</strong><small>Anyone with this link can open and answer the same quiz.</small><div class="kenzy-share-row"><input readonly value="${u.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"><button type="button">Copy link</button></div><small class="kenzy-share-note">The quiz is encoded in the link, so friends do not need your account.</small>`;page.querySelector('.quiz-toolbar')?.after(p);p.querySelector('button').onclick=async()=>{try{await navigator.clipboard.writeText(u);p.querySelector('button').textContent='Copied!';setTimeout(()=>p.querySelector('button').textContent='Copy link',1500);}catch{const i=p.querySelector('input');i.focus();i.select();document.execCommand('copy');}};}
function sharedPage(q){shareStyle();document.body.innerHTML=`<div style="max-width:780px;margin:0 auto;padding:40px 20px;font-family:system-ui;background:#f5f6fb;color:#11162a"><div style="display:flex;align-items:center;gap:10px;font-size:20px;font-weight:800;margin-bottom:28px"><span style="width:36px;height:36px;display:grid;place-items:center;border-radius:11px;background:#5b55e8;color:#fff">K</span>Kenzy</div><div id="kenzy-shared-box" style="background:#fff;border:1px solid #dfe3ed;border-radius:22px;padding:28px;box-shadow:0 18px 48px rgba(26,32,56,.09)"></div></div>`;const box=document.getElementById('kenzy-shared-box');let i=0,a=Array(q.questions.length).fill(-1),seconds=Math.max(60,(q.timeLimit||10)*60),timer=null;const esc=x=>String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');function render(){const x=q.questions[i];box.innerHTML=`<div style="color:#5b55e8;font-size:12px;font-weight:800;letter-spacing:.12em">SHARED QUIZ</div><div style="margin-top:10px;color:#5b55e8;font-weight:800">Question ${i+1} of ${q.questions.length} · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}</div><div style="height:8px;background:#eef0f7;border-radius:999px;overflow:hidden;margin:14px 0 22px"><span style="display:block;height:100%;width:${((i+1)/q.questions.length)*100}%;background:#5b55e8"></span></div><h1 style="font-size:clamp(28px,5vw,44px);line-height:1.12">${esc(x.question)}</h1><div>${x.options.map((o,n)=>`<button data-o="${n}" style="width:100%;display:block;text-align:left;padding:15px;margin:10px 0;border:1px solid ${a[i]===n?'#5b55e8':'#dfe3ed'};border-radius:14px;background:${a[i]===n?'#eeedff':'#fff'};cursor:pointer;color:#11162a"><b style="display:inline-grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#eef0f7;margin-right:10px">${String.fromCharCode(65+n)}</b>${esc(o)}</button>`).join('')}</div><div style="display:flex;justify-content:space-between;gap:10px;margin-top:22px"><button id="prev" ${i===0?'disabled':''} style="padding:12px 16px;border-radius:12px;border:1px solid #dfe3ed;background:#fff">← Previous</button><button id="next" style="padding:12px 16px;border-radius:12px;border:0;background:#5b55e8;color:#fff;font-weight:800">${i===q.questions.length-1?'Submit quiz':'Next →'}</button></div>`;box.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{a[i]=Number(b.dataset.o);render();});box.querySelector('#prev').onclick=()=>{if(i>0){i--;render();}};box.querySelector('#next').onclick=()=>{if(i===q.questions.length-1){clearInterval(timer);results();}else{i++;render();}};}
function results(){const c=a.reduce((n,v,j)=>n+(v===q.questions[j].correctIndex?1:0),0),score=Math.round(c/q.questions.length*100);box.innerHTML=`<div style="color:#5b55e8;font-size:12px;font-weight:800;letter-spacing:.12em">QUIZ COMPLETE</div><h1>${esc(q.title||'Shared quiz')}</h1><div style="font-size:64px;font-weight:900;color:#5b55e8">${score}/100</div><p>You got ${c} of ${q.questions.length} correct.</p><button id="again" style="padding:12px 16px;border:0;border-radius:12px;background:#5b55e8;color:#fff;font-weight:800">Take again</button>`;box.querySelector('#again').onclick=()=>{i=0;a=Array(q.questions.length).fill(-1);seconds=Math.max(60,(q.timeLimit||10)*60);start();};}function start(){clearInterval(timer);timer=setInterval(()=>{seconds--;if(seconds<=0){clearInterval(timer);results();}else if(document.getElementById('kenzy-shared-box'))render();},1000);render();}box.innerHTML=`<div style="color:#5b55e8;font-size:12px;font-weight:800;letter-spacing:.12em">SHARED QUIZ</div><h1>${esc(q.title||'Shared quiz')}</h1><p style="line-height:1.6;color:#66708a">A friend shared this quiz with you. Your answers are scored on this device and are not sent back to the creator.</p><button id="start" style="padding:12px 16px;border:0;border-radius:12px;background:#5b55e8;color:#fff;font-weight:800">Start quiz</button>`;box.querySelector('#start').onclick=start;}
function shareBoot(){const token=location.hash.match(/^#quiz=(.+)$/)?.[1];if(token){const q=shareDecode(decodeURIComponent(token));if(q){sharedPage(q);return;}}shareStyle();const obs=new MutationObserver(()=>{shareAccess();if(document.querySelector('.quiz-page'))shareOnQuiz();});obs.observe(document.body,{childList:true,subtree:true});shareAccess();shareOnQuiz();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',shareBoot);else shareBoot();
