const REVIEW_KEY='kenzy-quiz-review-v3';
const SHARE_VIS_KEY='kenzy-quiz-visibility-v3';
const SUGGESTION_KEY='kenzy-quiz-suggestion-v1';
let state={id:null,total:0,answered:{},marked:{}};
function load(){try{return JSON.parse(sessionStorage.getItem(REVIEW_KEY)||'{}');}catch{return {};}}
function save(){sessionStorage.setItem(REVIEW_KEY,JSON.stringify(state));}
function text(el){return(el?.textContent||'').replace(/\s+/g,' ').trim();}
function current(page){const m=text(page.querySelector('.question-count')).match(/Question\s+(\d+)/i);return m?+m[1]:1;}
function total(page){const m=text(page.querySelector('.question-count')).match(/of\s+(\d+)/i);return m?+m[1]:1;}
function maker(page){return !!page&&/Generate quiz/i.test(text(page.querySelector('button.button.primary.full-width')));}
function quiz(page){return !!page?.classList.contains('quiz-page');}
function remove(id){document.getElementById(id)?.remove();}
function setupNavigator(page){if(!quiz(page))return;const n=total(page),c=current(page),selected=!!page.querySelector('.answer-button.selected');if(!state.id||state.total!==n)state={id:`quiz-${Date.now()}`,total:n,answered:{},marked:{}};state.answered[c]=selected;save();let p=document.getElementById('quiz-upgrade-panel');if(!p){p=document.createElement('section');p.id='quiz-upgrade-panel';p.className='quiz-upgrade-panel';page.querySelector('.quiz-toolbar')?.after(p);}p.innerHTML=`<div class="quiz-upgrade-head"><div><strong>Question navigator</strong><small>Jump to a question or mark one to review later.</small></div><button class="quiz-mark-button ${state.marked[c]?'marked':''}" type="button">${state.marked[c]?'★ Marked for review':'☆ Mark for review'}</button></div><div class="quiz-upgrade-grid">${Array.from({length:n},(_,i)=>{const q=i+1;return `<button type="button" class="quiz-grid-dot ${q===c?'current':''} ${state.answered[q]?'answered':''} ${state.marked[q]?'marked':''}" data-q="${q}">${q}</button>`}).join('')}</div><div class="quiz-upgrade-legend"><span><i class="current"></i> Current</span><span><i class="answered"></i> Answered</span><span><i class="marked"></i> Review</span></div>`;p.querySelector('.quiz-mark-button').onclick=()=>{state.marked[c]=!state.marked[c];save();setupNavigator(page);};p.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>jumpTo(page,+b.dataset.q,c));}
function jumpTo(page,target,c){if(target===c)return;const next=target>c;const b=[...page.querySelectorAll('.quiz-navigation button')].find(x=>next?/Next/.test(text(x)):/Previous/.test(text(x)));if(!b)return;let steps=Math.abs(target-c);const go=()=>{if(!steps)return setupNavigator(page);b.click();steps--;setTimeout(go,30);};go();}
function style(){if(document.getElementById('kenzy-share-style'))return;const s=document.createElement('style');s.id='kenzy-share-style';s.textContent='.kenzy-visibility-panel,.kenzy-share-panel,.kenzy-suggestion-panel{margin:16px 0;padding:18px;background:var(--surface);border:1px solid var(--border);border-radius:18px;color:var(--text)}.kenzy-visibility-options{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.kenzy-visibility-option{display:flex;gap:10px;padding:13px;border:1px solid var(--border);border-radius:14px;background:var(--surface2);cursor:pointer}.kenzy-visibility-option.selected{border-color:var(--accent);box-shadow:0 0 0 3px rgba(91,85,232,.12)}.kenzy-visibility-option small,.kenzy-visibility-panel>small,.kenzy-share-panel>small{display:block;margin-top:4px;color:var(--muted);line-height:1.4}.kenzy-share-row{display:flex;gap:8px;margin-top:12px}.kenzy-share-row input,.kenzy-suggestion-panel textarea{min-width:0;width:100%;padding:11px;border:1px solid var(--border);border-radius:10px;background:var(--surface2);color:var(--text);outline:none}.kenzy-suggestion-panel textarea{margin-top:10px;resize:vertical;min-height:86px;line-height:1.5}.kenzy-suggestion-panel textarea:focus{border-color:var(--accent)}.kenzy-suggestion-examples{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.kenzy-suggestion-examples button{border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:9px;padding:7px 9px;font-size:11px;font-weight:800;cursor:pointer}.kenzy-suggestion-examples button:hover{border-color:var(--accent);color:var(--accent)}.kenzy-share-row button{border:0;border-radius:10px;padding:10px 14px;background:var(--accent);color:#fff;font-weight:800;cursor:pointer}@media(max-width:700px){.kenzy-visibility-options{grid-template-columns:1fr}.kenzy-share-row{flex-direction:column}}';document.head.appendChild(s);}
function enc(q){const b=new TextEncoder().encode(JSON.stringify({title:q.title,timeLimit:q.timeLimit,questions:q.questions}));let s='';b.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function dec(t){try{const p=t.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-t.length%4)%4);const b=atob(p);const u=Uint8Array.from(b,c=>c.charCodeAt(0));const q=JSON.parse(new TextDecoder().decode(u));return q&&Array.isArray(q.questions)&&q.questions.length?q:null;}catch{return null;}}
function url(q){return`${location.origin}${location.pathname}#quiz=${encodeURIComponent(enc(q))}`;}
function latest(){try{return JSON.parse(localStorage.getItem('kenzy-quizzes-v4')||'[]')[0]||null;}catch{return null;}}
function setupSuggestion(page){if(document.getElementById('kenzy-suggestion-panel')||!maker(page))return;style();const p=document.createElement('section');p.id='kenzy-suggestion-panel';p.className='kenzy-suggestion-panel';const saved=sessionStorage.getItem(SUGGESTION_KEY)||'';p.innerHTML=`<strong>Optional quiz request</strong><small>Tell Kenzy how you want the quiz made. For example: “Please include difficult problem-solving questions.”</small><textarea id="kenzy-quiz-suggestion" maxlength="1000" placeholder="Example: Please provide problem-solving questions and make them really difficult.">${saved.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</textarea><div class="kenzy-suggestion-examples"><button type="button" data-suggestion="Please include difficult problem-solving questions.">Difficult problem solving</button><button type="button" data-suggestion="Focus on tricky concepts and common mistakes.">Tricky concepts</button><button type="button" data-suggestion="Mix conceptual questions with application and solving questions.">Mix concepts + solving</button></div>`;const button=page.querySelector('button.button.primary.full-width');button?.parentElement?.before(p);const input=p.querySelector('#kenzy-quiz-suggestion');input?.addEventListener('input',()=>sessionStorage.setItem(SUGGESTION_KEY,input.value));p.querySelectorAll('[data-suggestion]').forEach(b=>b.onclick=()=>{if(!input)return;input.value=b.dataset.suggestion;sessionStorage.setItem(SUGGESTION_KEY,input.value);input.focus();});}
function installSuggestionFetch(){if(window.__kenzyQuizSuggestionFetch)return;const nativeFetch=window.fetch.bind(window);window.fetch=async(input,init)=>{const urlValue=typeof input==='string'?input:(input?.url||'');if(urlValue.includes('/api/generate-quiz')&&init?.body){try{const body=JSON.parse(init.body);const suggestion=document.getElementById('kenzy-quiz-suggestion')?.value?.trim()||sessionStorage.getItem(SUGGESTION_KEY)||'';body.suggestion=suggestion.slice(0,1000);init={...init,body:JSON.stringify(body)};}catch{}}return nativeFetch(input,init);};window.__kenzyQuizSuggestionFetch=true;}
function setupMaker(page){if(!maker(page))return;style();setupSuggestion(page);remove('kenzy-visibility-panel');const btn=page.querySelector('button.button.primary.full-width');if(!btn)return;const mode=sessionStorage.getItem(SHARE_VIS_KEY)||'personal';const p=document.createElement('section');p.id='kenzy-visibility-panel';p.className='kenzy-visibility-panel';p.innerHTML=`<strong>Quiz access</strong><small>Choose whether this quiz is personal or shareable with friends.</small><div class="kenzy-visibility-options"><label class="kenzy-visibility-option ${mode==='personal'?'selected':''}"><input type="radio" name="kenzy-visibility" value="personal" ${mode==='personal'?'checked':''}><span><b>Personal</b><small>Keep it in your Kenzy app like the original quiz.</small></span></label><label class="kenzy-visibility-option ${mode==='shareable'?'selected':''}"><input type="radio" name="kenzy-visibility" value="shareable" ${mode==='shareable'?'checked':''}><span><b>Shareable</b><small>Create a link friends can open and answer.</small></span></label></div>`;btn.parentElement?.before(p);p.querySelectorAll('input').forEach(i=>i.onchange=()=>{sessionStorage.setItem(SHARE_VIS_KEY,i.value);p.querySelectorAll('.kenzy-visibility-option').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked));});}
function setupShare(page){remove('kenzy-share-panel');if(!quiz(page))return;const q=latest();if(!q||q.visibility!=='shareable')return;style();const u=url(q);const p=document.createElement('section');p.id='kenzy-share-panel';p.className='kenzy-share-panel';p.innerHTML=`<strong>Share this quiz with friends</strong><small>Anyone with this link can open and answer the same quiz.</small><div class="kenzy-share-row"><input readonly value="${u.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"><button type="button">Copy link</button></div>`;page.querySelector('.quiz-toolbar')?.after(p);p.querySelector('button').onclick=async()=>{try{await navigator.clipboard.writeText(u);p.querySelector('button').textContent='Copied!';}catch{const i=p.querySelector('input');i.focus();i.select();document.execCommand('copy');}};}
function markVisibility(){try{const rows=JSON.parse(localStorage.getItem('kenzy-quizzes-v4')||'[]');if(rows.length)rows[0].visibility=sessionStorage.getItem(SHARE_VIS_KEY)||'personal';localStorage.setItem('kenzy-quizzes-v4',JSON.stringify(rows));}catch{}}
function shared(){const t=location.hash.match(/^#quiz=(.+)$/)?.[1];if(!t)return false;const q=dec(decodeURIComponent(t));if(!q)return false;document.body.innerHTML=`<main class="kenzy-shared-page"><div class="kenzy-shared-brand"><span>K</span>Kenzy</div><section id="kenzy-shared-box"></section></main>`;const box=document.getElementById('kenzy-shared-box');let i=0,a=Array(q.questions.length).fill(-1),sec=Math.max(60,(q.timeLimit||10)*60),timer;const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');function result(){clearInterval(timer);const c=a.reduce((n,v,j)=>n+(v===q.questions[j].correctIndex?1:0),0),score=Math.round(c/q.questions.length*100);box.innerHTML=`<div class="shared-eyebrow">QUIZ COMPLETE</div><h1>${esc(q.title||'Shared quiz')}</h1><div class="shared-score">${score}/100</div><p>You got ${c} of ${q.questions.length} correct.</p><button class="shared-primary" id="again">Take again</button>`;box.querySelector('#again').onclick=()=>{i=0;a.fill(-1);sec=Math.max(60,(q.timeLimit||10)*60);start();};}function render(){const x=q.questions[i];box.innerHTML=`<div class="shared-eyebrow">SHARED QUIZ</div><div class="shared-meta">Question ${i+1} of ${q.questions.length} · ${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}</div><h1>${esc(x.question)}</h1><div class="shared-options">${x.options.map((o,n)=>`<button data-o="${n}" class="shared-option ${a[i]===n?'selected':''}"><b>${String.fromCharCode(65+n)}</b>${esc(o)}</button>`).join('')}</div><div class="shared-nav"><button id="prev" ${i===0?'disabled':''}>← Previous</button><button id="next">${i===q.questions.length-1?'Submit quiz':'Next →'}</button></div>`;box.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{a[i]=+b.dataset.o;render();});box.querySelector('#prev').onclick=()=>{if(i>0){i--;render();}};box.querySelector('#next').onclick=()=>{if(i===q.questions.length-1)result();else{i++;render();}};}function start(){clearInterval(timer);timer=setInterval(()=>{sec--;if(sec<=0)result();else render();},1000);render();}box.innerHTML=`<div class="shared-eyebrow">SHARED QUIZ</div><h1>${esc(q.title||'Shared quiz')}</h1><p>A friend shared this quiz with you. Your answers are scored on this device.</p><button class="shared-primary" id="start">Start quiz</button>`;box.querySelector('#start').onclick=start;return true;}
function tick(){if(shared())return;const page=document.querySelector('.page');remove('kenzy-visibility-panel');remove('kenzy-share-panel');if(maker(page)){setupMaker(page);markVisibility();}else if(quiz(page)){setupNavigator(page);setupShare(page);}}
function boot(){if(window.__kenzyQuizUpgradeV3)return;window.__kenzyQuizUpgradeV3=true;state=load();installSuggestionFetch();tick();window.setInterval(tick,500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();